package:
  name: "cadabra2-jupyter-kernel"
  version: "2.2.9"

source:
  path: ../  

requirements:
  build:
    - python
    - setuptools
    - boost 1.67.*	 
    - libboost 1.67.*
    - cmake
    - pkg-config
    - glibmm
    - zeromq
    - cppzmq
    - xtl
    - cryptopp
    - sqlite
    - util-linux
    - xeus
    - nlohmann_json
    - sympy
    - jupyter

  run:
    - python
    - jupyter
    - libstdcxx-ng
    - libgcc-ng
    - gmp    
    - glibmm
    - xeus
    - libboost 1.67.*

# outputs:
#   - name: "cadabra2-jupyter-kernel"
#     files:
#       - bin/cadabra-jupyter-kernel
#       - share/jupyter/kernels/
#       - share/cadabra2/

about:
  home: https://cadabra.science
  license: GPL
  license_family: GPL
  summary: Jupyter kernel for the Cadabra2 computer algebra system.
