name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    python-version: 3.6
    
    steps:
    - uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v2
      with:
          python-version: 3.6
    - name: get dependencies
      run:  sudo apt-get install git cmake python3-dev g++ libpcre3 libpcre3-dev libgmp3-dev libgtkmm-3.0-dev libboost-all-dev libgmp-dev libsqlite3-dev uuid-dev texlive-base python3-mpmath && python -m pip install sympy
    - name: configure
      run:  mkdir build && cd build && cmake -DENABLE_MATHEMATICA=OFF ..
    - name: make
      run:  cd build && make
    - name: make test
      run:  cd build && make test ARGS="-V"
