name: macOS-monterey

on: [push]

jobs:
  build:

    runs-on: macos-12
    
    steps:
    - uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: 3.11

    - name: get dependencies
      run:  brew install cmake boost pcre gmp python3 pkgconfig gtkmm3 adwaita-icon-theme && /usr/local/bin/python3 -m pip install sympy gmpy2 numpy

    - name: configure
      run:  mkdir build && cd build && cmake -DENABLE_MATHEMATICA=OFF ..
      
    - name: make
      run:  cd build && make
      
    - name: make test
      run:  cd build && make test ARGS="-V"
