# This is a build which gets triggered on every commit push,
# to test whether the homebrew package works.

name: testbrew-devel

on:
  workflow_run:
    workflows: ["Homebrew-devel"]
    types:
      - completed

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: get dependencies
      run:  brew tap kpeeters/repo && brew install cadabra2-devel

    - name: show
      run:  cat `which cadabra2`
      
    - name: test
      run:  echo "A+B;\nquit()\n" > tst.cdb && cadabra2 tst.cdb
